### ISSUE TITLE
Having issues installing on OPNsense 24.7.11_2-amd64

### ISSUE THREAD

**Issue by fuzzylogicbits** [opncell/opncell#17]
Hello, 
I am having issue in getting the opncell plugin running. 

Fresh install : 
OPNsense 24.7.11_2-amd64
FreeBSD 14.1-RELEASE-p6
OpenSSL 3.0.15

Installed as per instructions:- 
I noticed that the instructions indicate that Mongodb  should be //localhost: 9999 
however the install showed it running on port 3000.

**hss does not start up.** 
Shows the following error in the log:- 

===========================

 ```
root@OPNsense:/usr/local/etc/open5gs # cat /var/log/opncell/hss.log
Open5GS daemon v2.7.2-1-g3743097

01/08 21:39:46.244: [app] INFO: Configuration: '/usr/local/etc/open5gs/hss.yaml' (../lib/app/ogs-init.c:133)
01/08 21:39:46.244: [app] INFO: File Logging: '/var/log/opncell/hss.log' (../lib/app/ogs-init.c:136)
01/08 21:39:46.258: [dbi] WARNING: Failed to connect to server [mongodb://localhost/open5gs] (../lib/dbi/ogs-mongoc.c:122)
01/08 21:39:46.258: [app] WARNING: Failed to initialize HSS (../src/hss/app-init.c:28)
Open5GS daemon v2.7.2-1-g3743097

01/08 21:49:18.415: [app] INFO: Configuration: '/usr/local/etc/open5gs/hss.yaml' (../lib/app/ogs-init.c:133)
01/08 21:49:18.415: [app] INFO: File Logging: '/var/log/opncell/hss.log' (../lib/app/ogs-init.c:136)
01/08 21:49:18.428: [dbi] WARNING: Failed to connect to server [mongodb://localhost:3000/open5gs] (../lib/dbi/ogs-mongoc.c:122)
01/08 21:49:18.428: [app] WARNING: Failed to initialize HSS (../src/hss/app-init.c:28)
root@OPNsense:/usr/local/etc/open5gs #
```

I am able to connect  via cli command 
 ```
mongo mongodb://localhost:3000/open5gs
MongoDB shell version v5.0.27
connecting to: mongodb://localhost:3000/open5gs?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("39d23a93-3752-44d1-bcec-1595df604483") }
MongoDB server version: 5.0.27
================
Warning: the "mongo" shell has been superseded by "mongosh",
which delivers improved usability and compatibility.The "mongo" shell has been deprecated and will be removed in
an upcoming release.
For installation instructions, see
https://docs.mongodb.com/mongodb-shell/install/
================
---
The server generated these startup warnings when booting:
        2025-01-08T21:38:13.691+00:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
        2025-01-08T21:38:13.691+00:00: You are running this process as the root user, which is not recommended
---
===================================
```

Any and all suggestions would be greatly appreciated. 

Thank you
Faisal

**Comment by rhamblet** [comment]
Faisal,

Did you reboot after installation?  The Mongod port shouldn’t make a difference.  You will also need to ensure you have rules to allow the conversations.  Try disabling the packet filter - “pf -d”  Likely SCTP is being blocked as well.

￼

Regards,

Rob Hamblet
Chief Technology Officer

￼
The information contained in this message and any attachments (collectively, the "Transmission") contains proprietary and/or confidential information of the sender’s employer which is protected from disclosure and intended solely for the named recipient(s). If you are not a named recipient, you are prohibited from copying, distributing or using this Transmission. Please contact the sender immediately by returning the e-mail and deleting the original Transmission.

**Comment by rhamblet** [comment]
![image](https://github.com/user-attachments/assets/abd132f9-2db1-48c5-8a67-7b6533a75aa3)

**Comment by fuzzylogicbits** [comment]
Thank you for the quick response. 
I did a reboot and that fixed the HSS issue. 
(I did have the floating rule installed, and added the additional rules you suggested). 
Now only the pcrf is not starting .. 

![image](https://github.com/user-attachments/assets/481b132c-2163-4064-af32-ae605c0dbfde)

Firewall floating rules .. 
![image](https://github.com/user-attachments/assets/df3cf20f-3d60-4fc9-b983-f22b0e9e2dc2)

![image](https://github.com/user-attachments/assets/2335cc01-37e0-4d65-8766-7adca82e8f6c)

**Comment by rhamblet** [comment]
Have a look at /usr/local/etc/open5gs/pcrf.yaml (it’s config file)  It should look like:

db_uri: mongodb://localhost/open5gs
logger:
  file:
    path: /usr/ports/open5gs/install/var/log/open5gs/pcrf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace
global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64
pcrf:
  freeDiameter: /usr/ports/open5gs/install/etc/freeDiameter/pcrf.conf

What does the /var/log/opncell/pcrf.log illustrate?

-Rob

**Comment by rhamblet** [comment]
Try to manually start the pcrf service with the green start button

**Comment by fuzzylogicbits** [comment]
pcrf.yaml file 
```
 cat /usr/local/etc/open5gs/pcrf.yaml
db_uri: mongodb://localhost/open5gs
logger:
  file:
    path: /usr/ports/open5gs/install/var/log/open5gs/pcrf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64
pcrf:
  freeDiameter: /usr/ports/open5gs/install/etc/freeDiameter/pcrf.conf

################################################################################
# Locally configured policy
################################################################################
#
#  o You don't have to use MongoDB if you use the policy configuration as below.
#
#  session:
#    - name: internet
#      type: 3  # 1:IPv4, 2:IPv6, 3:IPv4v6
#      ambr:
#        downlink:
#          value: 1
#          unit: 3  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
#        uplink:
#          value: 1
#          unit: 3
#      qos:
#        index: 9  # 1, 2, 3, 4, 65, 66, 67, 75, 71, 72, 73, 74, 76, 5, 6, 7, 8, 9, 69, 70, 79, 80, 82, 83, 84, 85, 86
#        arp:
#          priority_level: 8  # 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
#          pre_emption_vulnerability: 1  # 1: Disabled, 2:Enabled
#          pre_emption_capability: 1  # 1: Disabled, 2:Enabled
#    - name: ims
#      type: 3  # 1:IPv4, 2:IPv6, 3:IPv4v6
#      ambr:
#        downlink:
#          value: 1
#          unit: 3  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
#        uplink:
#          value: 1
#          unit: 3  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
#      qos:
#        index: 5  # 1, 2, 3, 4, 65, 66, 67, 75, 71, 72, 73, 74, 76, 5, 6, 7, 8, 9, 69, 70, 79, 80, 82, 83, 84, 85, 86
#        arp:
#          priority_level: 1  # 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
#          pre_emption_vulnerability: 1  # 1: Disabled, 2:Enabled
#          pre_emption_capability: 1  # 1: Disabled, 2:Enabled
#      pcc_rule:
#        - qos:
#            index: 1  # 1, 2, 3, 4, 65, 66, 67, 75, 71, 72, 73, 74, 76, 5, 6, 7, 8, 9, 69, 70, 79, 80, 82, 83, 84, 85, 86
#            arp:
#              priority_level: 1  # 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
#              pre_emption_vulnerability: 1   # 1: Disabled, 2:Enabled
#              pre_emption_capability: 1   # 1: Disabled, 2:Enabled
#            mbr:
#              downlink:
#                value: 82
#                unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
#              uplink:
#                value: 82
#                unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
#            gbr:
#              downlink:
#                value: 82
#                unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
#              uplink:
#                value: 82
#                unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
#          flow:
#            - direction: 2
#              description: "permit out icmp from any to assigned"
#            - direction: 1
#              description: "permit out icmp from any to assigned"
#            - direction: 2
#              description: "permit out udp from 10.200.136.98/32 23455 to assigned 1-65535"
#            - direction: 1
#              description: "permit out udp from 10.200.136.98/32 1-65535 to assigned 50021"
#        - qos:
#            index: 2  # 1, 2, 3, 4, 65, 66, 67, 75, 71, 72, 73, 74, 76, 5, 6, 7, 8, 9, 69, 70, 79, 80, 82, 83, 84, 85, 86
#            arp:
#              priority_level: 4  # 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
#              pre_emption_vulnerability: 2   # 1: Disabled, 2:Enabled
#              pre_emption_capability: 2   # 1: Disabled, 2:Enabled
#            mbr:
#              downlink:
#                value: 802
#                unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
#              uplink:
#                value: 802
#                unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
#            gbr:
#              downlink:
#                value: 802
#                unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
#              uplink:
#                value: 802
#                unit: 1  # 0:bps, 1:Kbps, 2:Mbps, 3:Gbps, 4:Tbps
#

```
log file .. 
```

 cat /var/log/opncell/pcrf.log
Open5GS daemon v2.7.2-1-g3743097

01/08 22:32:57.264: [app] INFO: Configuration: '/usr/local/etc/open5gs/pcrf.yaml' (../lib/app/ogs-init.c:133)
01/08 22:32:57.264: [app] INFO: File Logging: '/var/log/opncell/pcrf.log' (../lib/app/ogs-init.c:136)
01/08 22:32:57.276: [dbi] WARNING: Failed to connect to server [mongodb://localhost/open5gs] (../lib/dbi/ogs-mongoc.c:122)
01/08 22:32:57.276: [app] WARNING: Failed to initialize PCRF (../src/pcrf/app-init.c:28)
Open5GS daemon v2.7.2-1-g3743097

01/08 22:35:51.835: [app] INFO: Configuration: '/usr/local/etc/open5gs/pcrf.yaml' (../lib/app/ogs-init.c:133)
01/08 22:35:51.835: [app] INFO: File Logging: '/var/log/opncell/pcrf.log' (../lib/app/ogs-init.c:136)
01/08 22:35:51.847: [dbi] WARNING: Failed to connect to server [mongodb://localhost/open5gs] (../lib/dbi/ogs-mongoc.c:122)
01/08 22:35:51.847: [app] WARNING: Failed to initialize PCRF (../src/pcrf/app-init.c:28)
Open5GS daemon v2.7.2-1-g3743097

01/08 22:36:50.670: [app] INFO: Configuration: '/usr/local/etc/open5gs/pcrf.yaml' (../lib/app/ogs-init.c:133)
01/08 22:36:50.670: [app] INFO: File Logging: '/var/log/opncell/pcrf.log' (../lib/app/ogs-init.c:136)
01/08 22:36:50.682: [dbi] WARNING: Failed to connect to server [mongodb://localhost/open5gs] (../lib/dbi/ogs-mongoc.c:122)
01/08 22:36:50.682: [app] WARNING: Failed to initialize PCRF (../src/pcrf/app-init.c:28)
root@OPNsense:~ #

```
restarting by pressing the service start button, yeilds the following in the logs:- 

```
01/08 23:09:27.514: [app] INFO: Configuration: '/usr/local/etc/open5gs/pcrf.yaml' (../lib/app/ogs-init.c:133)
01/08 23:09:27.514: [app] INFO: File Logging: '/var/log/opncell/pcrf.log' (../lib/app/ogs-init.c:136)
01/08 23:09:27.526: [dbi] WARNING: Failed to connect to server [mongodb://localhost/open5gs] (../lib/dbi/ogs-mongoc.c:122)
01/08 23:09:27.526: [app] WARNING: Failed to initialize PCRF (../src/pcrf/app-init.c:28)
root@OPNsense:~ #


```
